### ISSUE TITLE
Add .canvas-active class to body when offcanvas is initiated.

### ISSUE THREAD

**Issue by seb2point0** [jasny/bootstrap#369]
I propose a `canvas-active` class be added to the body tag from the moment the menu is called to when it is completely closed. This would make it easier to do things like apply opacity to the canvas, and specifically, manage css transitions. This is currently difficult to do because `canvas-sliding` is only shown during the transition, and `canvas-slid` is only added while the menu is opened.

**Comment by jasny** [comment]
I'll think about it. For now I'm tending to not implement this. Using both classes it pretty easy. Adding another class it yet another moving part.

```css
.canvas-sliding,
.canvas-slid {
  .my-message {
    color: red;
  }
}
```

**Comment by seb2point0** [comment]
Yes, that is one way to look at it. However, I'll have to see if it will work with transitions. In my case, I want the canvas to transition to and from 0.5 opacity during the open and close animations. I don't know if that is possible using only CSS with these classes.

**Comment by jasny** [comment]
It is possible with these classes. It wouldn't be possible with `canvas-active`.

```css
.canvas {
  opacity: 1;
  transition: opacity 1s;
}
.canvas.canvas-sliding {
  opacity: 0.5;
}
.canvas.canvas-slid {
  opacity: 1;  
}
```

For more questions, please use [StackOverflow](http://www.stackoverflow)
