### ISSUE TITLE
Offcanvas drop shadow for slide-in overlay

### ISSUE THREAD

**Issue by aadrian** [jasny/bootstrap#474]
Please add a light drop shadow for the slide-in overlay for the offcanvas component to make it visible that it's an overlay.

Thank you.

**Comment by aadrian** [comment]
```css
.navmenu {
  padding-top: 50px;
  -webkit-box-shadow: 0px 0px 8px 0px rgba(204,204,204,.75);
  -moz-box-shadow: 0px 0px 8px 0px rgba(204,204,204,.75);
  box-shadow: 0px 0px 8px 0px rgba(204,204,204,.75);
}
```
